package com.example.remembranceagent.ui

val GOOGLE_CLOUD_API_KEY: String = "GOOGLE_CLOUD_API_KEY"
val DOCUMENTS_PATH_STRING_KEY: String = "DOCUMENTS_PATH_STRING"
val INDEX_PATH_STRING_KEY: String = "INDEX_PATH_STRING"
